// <auto-generated />
using System;
using MVCHulladek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCHulladek.Migrations
{
    [DbContext(typeof(MVCHulladekContext))]
    partial class MVCHulladekContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCHulladek.Models.Lakig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Igeny")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.Property<int>("SzolgaltatasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SzolgaltatasId");

                    b.ToTable("Lakig");
                });

            modelBuilder.Entity("MVCHulladek.Models.Naptar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("SzolgaltatasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SzolgaltatasId");

                    b.ToTable("Naptar");
                });

            modelBuilder.Entity("MVCHulladek.Models.Szolgaltatas", b =>
                {
                    b.Property<int>("SzolgaltatasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SzolgaltatasId"));

                    b.Property<string>("Jelentes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SzolgaltatasId");

                    b.ToTable("Szolgaltatas");
                });

            modelBuilder.Entity("MVCHulladek.Models.Lakig", b =>
                {
                    b.HasOne("MVCHulladek.Models.Szolgaltatas", "Szolgaltatas")
                        .WithMany()
                        .HasForeignKey("SzolgaltatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szolgaltatas");
                });

            modelBuilder.Entity("MVCHulladek.Models.Naptar", b =>
                {
                    b.HasOne("MVCHulladek.Models.Szolgaltatas", "Szolgaltatas")
                        .WithMany()
                        .HasForeignKey("SzolgaltatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szolgaltatas");
                });
#pragma warning restore 612, 618
        }
    }
}
